### ISSUE TITLE
Produces a dist folder with local references

### ISSUE THREAD

**Issue by jorisw** [chromaui/learnstorybook-design-system#9] opened 2020-05-01 08:18 UTC
I've started with a clean copy of the this repo, hit `yarn build`, and `dist/` is now full of references to my local hard drive:

![image](https://user-images.githubusercontent.com/30017/80792541-f3cde880-8b94-11ea-81ed-7e24d2600575.png)

**Comment by jonniebigodes** [comment] 2021-07-15 22:53
Closing this issue as it's no longer applicable with the latest version. The issue is missing information related to babel. Which is already documented.

**Closed as completed by jonniebigodes** 2021-07-15 22:53 UTC
